#!/usr/bin/env python3
"""Generate src/stat_registry.rs from the installed axisregistry package.

The embedded table mirrors `axisregistry.axis_registry` (the GF axis
registry .textproto data): tag, display_name, default_value and the
fallback list per axis, IN THE PACKAGE'S OWN ITERATION ORDER. That order
matters: `AxisRegistry.get_fallback(name)` returns the first axis in
registry order carrying a fallback with that name, and the Python
package's order is the .textproto directory's iterdir() order (stable
for a given install). Ambiguous fallback names across axes are only
"Default", "Normal" and "Roman".

Usage: .venv/bin/python wasm/fontc-web/spike/gen_stat_registry.py
Re-run when the venv's axisregistry package is upgraded.
"""
import os

from axisregistry import axis_registry

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "stat_registry.rs")


def rust_str(s):
    # The registry strings are printable ASCII; escape defensively anyway.
    assert all(32 <= ord(c) < 127 for c in s), f"non-ASCII registry string: {s!r}"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    lines = [
        "//! GENERATED by spike/gen_stat_registry.py from the installed",
        "//! axisregistry package (GF axis registry .textproto data). Do not",
        "//! edit by hand; re-run the generator when axisregistry changes.",
        "//!",
        "//! Order matters: `get_fallback` (stat.rs) returns the first axis",
        "//! in this order carrying a fallback with a given name, matching",
        "//! the Python package's registry iteration order.",
        "",
        "/// One GF axis-registry fallback: a named location on an axis.",
        "pub(crate) struct AxisFallback {",
        "    pub name: &'static str,",
        "    pub value: f64,",
        "}",
        "",
        "/// One axis in the GF axis registry.",
        "pub(crate) struct RegistryAxis {",
        "    pub tag: &'static str,",
        "    pub display_name: &'static str,",
        "    pub default_value: f64,",
        "    pub fallbacks: &'static [AxisFallback],",
        "}",
        "",
        "/// The GF axis registry, in the Python package's iteration order.",
        "pub(crate) static AXIS_REGISTRY: &[RegistryAxis] = &[",
    ]
    for tag in axis_registry:
        axis = axis_registry[tag]
        assert len(tag) == 4 and tag.isascii(), f"bad tag {tag!r}"
        for f in [axis.default_value] + [fb.value for fb in axis.fallback]:
            # fontTools fl2fi(v,16) == Fixed::from_f64(v) holds exactly
            # for dyadic values; keep the port honest by enforcing it.
            assert f * 65536 == int(f * 65536), f"{tag}: {f} not 16.16-exact"
        fallbacks = ", ".join(
            f"AxisFallback {{ name: {rust_str(fb.name)}, value: {fb.value!r} }}"
            for fb in axis.fallback
        )
        lines.append(
            f"    RegistryAxis {{ tag: {rust_str(tag)},"
            f" display_name: {rust_str(axis.display_name)},"
            f" default_value: {axis.default_value!r},"
            f" fallbacks: &[{fallbacks}] }},"
        )
    lines.append("];")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT)} ({len(axis_registry.keys())} axes)")


if __name__ == "__main__":
    main()
