//! GENERATED by spike/gen_stat_registry.py from the installed
//! axisregistry package (GF axis registry .textproto data). Do not
//! edit by hand; re-run the generator when axisregistry changes.
//!
//! Order matters: `get_fallback` (stat.rs) returns the first axis
//! in this order carrying a fallback with a given name, matching
//! the Python package's registry iteration order.

/// One GF axis-registry fallback: a named location on an axis.
pub(crate) struct AxisFallback {
    pub name: &'static str,
    pub value: f64,
}

/// One axis in the GF axis registry.
pub(crate) struct RegistryAxis {
    pub tag: &'static str,
    pub display_name: &'static str,
    pub default_value: f64,
    pub fallbacks: &'static [AxisFallback],
}

/// The GF axis registry, in the Python package's iteration order.
pub(crate) static AXIS_REGISTRY: &[RegistryAxis] = &[
    RegistryAxis { tag: "INFM", display_name: "Informality", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "GRAD", display_name: "Grade", default_value: 0.0, fallbacks: &[AxisFallback { name: "Normal", value: 0.0 }] },
    RegistryAxis { tag: "slnt", display_name: "Slant", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "ARRR", display_name: "AR Retinal Resolution", default_value: 10.0, fallbacks: &[AxisFallback { name: "Default", value: 10.0 }] },
    RegistryAxis { tag: "XOPQ", display_name: "Thick Stroke", default_value: 88.0, fallbacks: &[AxisFallback { name: "Normal", value: 88.0 }] },
    RegistryAxis { tag: "XTRA", display_name: "Counter Width", default_value: 400.0, fallbacks: &[AxisFallback { name: "Normal", value: 400.0 }] },
    RegistryAxis { tag: "opsz", display_name: "Optical Size", default_value: 14.0, fallbacks: &[AxisFallback { name: "6pt", value: 6.0 }, AxisFallback { name: "7pt", value: 7.0 }, AxisFallback { name: "8pt", value: 8.0 }, AxisFallback { name: "9pt", value: 9.0 }, AxisFallback { name: "10pt", value: 10.0 }, AxisFallback { name: "11pt", value: 11.0 }, AxisFallback { name: "12pt", value: 12.0 }, AxisFallback { name: "14pt", value: 14.0 }, AxisFallback { name: "16pt", value: 16.0 }, AxisFallback { name: "17pt", value: 17.0 }, AxisFallback { name: "18pt", value: 18.0 }, AxisFallback { name: "20pt", value: 20.0 }, AxisFallback { name: "24pt", value: 24.0 }, AxisFallback { name: "28pt", value: 28.0 }, AxisFallback { name: "36pt", value: 36.0 }, AxisFallback { name: "48pt", value: 48.0 }, AxisFallback { name: "60pt", value: 60.0 }, AxisFallback { name: "72pt", value: 72.0 }, AxisFallback { name: "96pt", value: 96.0 }, AxisFallback { name: "120pt", value: 120.0 }, AxisFallback { name: "144pt", value: 144.0 }] },
    RegistryAxis { tag: "VOLM", display_name: "Volume", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YTFI", display_name: "Figure Height", default_value: 600.0, fallbacks: &[AxisFallback { name: "Normal", value: 600.0 }] },
    RegistryAxis { tag: "XPN2", display_name: "Horizontal Position of Paint 2", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "SCAN", display_name: "Scanlines", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "EDPT", display_name: "Extrusion Depth", default_value: 100.0, fallbacks: &[AxisFallback { name: "Default", value: 100.0 }] },
    RegistryAxis { tag: "XELA", display_name: "Horizontal Element Alignment", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "ital", display_name: "Italic", default_value: 0.0, fallbacks: &[AxisFallback { name: "Roman", value: 0.0 }, AxisFallback { name: "Italic", value: 1.0 }] },
    RegistryAxis { tag: "SZP2", display_name: "Size of Paint 2", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YPN2", display_name: "Vertical Position of Paint 2", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YOPQ", display_name: "Thin Stroke", default_value: 116.0, fallbacks: &[AxisFallback { name: "Normal", value: 116.0 }] },
    RegistryAxis { tag: "SHLN", display_name: "Shadow Length", default_value: 50.0, fallbacks: &[AxisFallback { name: "Default", value: 50.0 }] },
    RegistryAxis { tag: "YELA", display_name: "Vertical Element Alignment", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "XROT", display_name: "Rotation in X", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "SHRP", display_name: "Sharpness", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "XTFI", display_name: "X transparent figures", default_value: 400.0, fallbacks: &[AxisFallback { name: "Normal", value: 400.0 }] },
    RegistryAxis { tag: "CRSV", display_name: "Cursive", default_value: 0.5, fallbacks: &[AxisFallback { name: "Roman", value: 0.0 }, AxisFallback { name: "Auto", value: 0.5 }, AxisFallback { name: "Cursive", value: 1.0 }] },
    RegistryAxis { tag: "SZP1", display_name: "Size of Paint 1", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YROT", display_name: "Rotation in Y", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YPN1", display_name: "Vertical Position of Paint 1", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "BNCE", display_name: "Bounce", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YTDE", display_name: "Descender Depth", default_value: -250.0, fallbacks: &[AxisFallback { name: "Normal", value: -250.0 }] },
    RegistryAxis { tag: "WONK", display_name: "Wonky", default_value: 0.0, fallbacks: &[AxisFallback { name: "NonWonky", value: 0.0 }, AxisFallback { name: "Wonky", value: 1.0 }] },
    RegistryAxis { tag: "CASL", display_name: "Casual", default_value: 0.0, fallbacks: &[AxisFallback { name: "Linear", value: 0.0 }, AxisFallback { name: "Casual", value: 1.0 }] },
    RegistryAxis { tag: "wght", display_name: "Weight", default_value: 400.0, fallbacks: &[AxisFallback { name: "Thin", value: 100.0 }, AxisFallback { name: "ExtraLight", value: 200.0 }, AxisFallback { name: "Light", value: 300.0 }, AxisFallback { name: "Regular", value: 400.0 }, AxisFallback { name: "Medium", value: 500.0 }, AxisFallback { name: "SemiBold", value: 600.0 }, AxisFallback { name: "Bold", value: 700.0 }, AxisFallback { name: "ExtraBold", value: 800.0 }, AxisFallback { name: "Black", value: 900.0 }] },
    RegistryAxis { tag: "BLED", display_name: "Bleed", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "HEXP", display_name: "Hyper Expansion", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "ELXP", display_name: "Element Expansion", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "ZROT", display_name: "Rotation in Z", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YTLC", display_name: "Lowercase Height", default_value: 500.0, fallbacks: &[AxisFallback { name: "Normal", value: 500.0 }] },
    RegistryAxis { tag: "ELGR", display_name: "Element Grid", default_value: 1.0, fallbacks: &[AxisFallback { name: "Default", value: 1.0 }] },
    RegistryAxis { tag: "ELSH", display_name: "Element Shape", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YTUC", display_name: "Uppercase Height", default_value: 725.0, fallbacks: &[AxisFallback { name: "Normal", value: 725.0 }] },
    RegistryAxis { tag: "FILL", display_name: "Fill", default_value: 0.0, fallbacks: &[AxisFallback { name: "Normal", value: 0.0 }, AxisFallback { name: "Filled", value: 1.0 }] },
    RegistryAxis { tag: "MORF", display_name: "Morph", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "CTRS", display_name: "Contrast", default_value: 0.0, fallbacks: &[AxisFallback { name: "Reversed", value: -100.0 }, AxisFallback { name: "None", value: 0.0 }, AxisFallback { name: "High", value: 100.0 }] },
    RegistryAxis { tag: "YEAR", display_name: "Year", default_value: 2000.0, fallbacks: &[AxisFallback { name: "Default", value: 2000.0 }] },
    RegistryAxis { tag: "ROND", display_name: "Roundness", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "SOFT", display_name: "Softness", default_value: 0.0, fallbacks: &[AxisFallback { name: "Sharp", value: 0.0 }, AxisFallback { name: "Soft", value: 50.0 }, AxisFallback { name: "SuperSoft", value: 100.0 }] },
    RegistryAxis { tag: "YEXT", display_name: "Vertical Extension", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "YTAS", display_name: "Ascender Height", default_value: 750.0, fallbacks: &[AxisFallback { name: "Normal", value: 750.0 }] },
    RegistryAxis { tag: "wdth", display_name: "Width", default_value: 100.0, fallbacks: &[AxisFallback { name: "SuperCondensed", value: 25.0 }, AxisFallback { name: "UltraCondensed", value: 50.0 }, AxisFallback { name: "ExtraCondensed", value: 62.5 }, AxisFallback { name: "Condensed", value: 75.0 }, AxisFallback { name: "SemiCondensed", value: 87.5 }, AxisFallback { name: "Normal", value: 100.0 }, AxisFallback { name: "SemiExpanded", value: 112.5 }, AxisFallback { name: "Expanded", value: 125.0 }, AxisFallback { name: "ExtraExpanded", value: 150.0 }, AxisFallback { name: "UltraExpanded", value: 200.0 }] },
    RegistryAxis { tag: "EHLT", display_name: "Edge Highlight", default_value: 12.0, fallbacks: &[AxisFallback { name: "Default", value: 12.0 }] },
    RegistryAxis { tag: "MONO", display_name: "Monospace", default_value: 0.0, fallbacks: &[AxisFallback { name: "Proportional", value: 0.0 }, AxisFallback { name: "Monospace", value: 1.0 }] },
    RegistryAxis { tag: "SPAC", display_name: "Spacing", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "FLAR", display_name: "Flare", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
    RegistryAxis { tag: "XPN1", display_name: "Horizontal Position of Paint 1", default_value: 0.0, fallbacks: &[AxisFallback { name: "Default", value: 0.0 }] },
];
